export const ServerUrl = "https://chatting-web-app-2xe3.onrender.com/api"
export const SocketId = "https://chatting-socket-c5k9.onrender.com"
export const ServerUrli = "http://localhost:8081/api"
export const SocketIdi = "http://localhost:8080"
export const Server = "https://chatting-web-app-2xe3.onrender.com"
export const Serveri = "http://localhost:8081"